name: test

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: ${{ runner.os }}-npm-puppeteer
      - name: Install
        if: steps.cache-npm.outputs.cache-hit == 'false'
        run: npm install puppeteer
      - name: Run
        env:
          CORE_JS: ${{ vars.CORE_JS }}
          WORKER_URL: ${{ vars.WORKER_URL }}
        run: |
          echo "$CORE_JS" > index.js
          node index.js
