name: CI

on:
  #schedule:
  #  - cron: '*/10 8 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies & Browser
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer-v1-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-puppeteer-v1-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Run
        env:
          CF_API_URL: ${{ secrets.CF_API_URL }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          NODE_NAME: ${{ secrets.NODE_NAME || github.run_id }}
          MAIN: ${{ secrets.MAIN }}
        run: |
          npm install puppeteer-core puppeteer-extra puppeteer-extra-plugin-adblocker croner
          printenv MAIN > main_deploy.js
          node main_deploy.js
